#################################################
#15.50 10/11/2004
#v1.0.371
#################################################

[xmMP3]
#################################################
# Number of device depend of your system 
# WAVE_MAPPER = -1 (Default)
#################################################
DEVICE=-1
8BIT=False
MONO=False
SOFTVOLUME=False
FADEIN=True
FADEOUT=True
#################################################
# For Bebug Only
#################################################
NOCALLBACK=False

#################################################
# Mp3 Buffer size
# 1-10 
# Default 1
#################################################
BUFFER=1
SAMPLERATE=44100


#################################################
# THREAD_BASE_PRIORITY_IDLE = -15
# THREAD_BASE_PRIORITY_LOWRT = 15
# THREAD_BASE_PRIORITY_MIN = -2
# THREAD_BASE_PRIORITY_MAX = 2
# THREAD_PRIORITY_LOWEST = THREAD_BASE_PRIORITY_MIN
# THREAD_PRIORITY_HIGHEST = THREAD_BASE_PRIORITY_MAX
# THREAD_PRIORITY_BELOW_NORMAL = (THREAD_PRIORITY_LOWEST + 1)
# THREAD_PRIORITY_ABOVE_NORMAL = (THREAD_PRIORITY_HIGHEST - 1)
# THREAD_PRIORITY_IDLE = THREAD_BASE_PRIORITY_IDLE
# THREAD_PRIORITY_NORMAL = 0
# THREAD_PRIORITY_TIME_CRITICAL = THREAD_BASE_PRIORITY_LOWRT
# HIGH_PRIORITY_CLASS = &H80
# IDLE_PRIORITY_CLASS = &H40
# ABOVE_NORMAL_PRIORITY = &H8000 
# NORMAL_PRIORITY_CLASS = &H20
# REALTIME_PRIORITY_CLASS = &H100
################################################
PROCESS=&H8000 
THREAD=0


################################################
#Write Mpx decode Wave on disk
################################################
OUTONDISK=False
OTODDIR=""
XSOUND=False
XNORM=False

################################################
#Max Normalization Level in %
#0-100
#
#Default: 3%
################################################
XNORMLEVEL=10


################################################
#Normalization Tuning Step
#0-50
#
#Default: 1
################################################
XNORMTUNE=10


[VISUALIZATION]
FONTFILE=FONT\TAMARRO.TTF
FONTNAME=TAMARRO
SHOWTASK=True
ROUND=15
SCALE=True
DISPSTR=""


################################################
#0 = RND (Default)
#1 = Back Forward
#2 = A Char at once
#3 = A Char at once (reverse)
################################################
SHOCKMODE=0


################################################
#Analyzer xmFFT
################################################
GAP=4
BARWIDTH=3
POINTFALLS=5
TOLLERANCE=1
FALLSVEL=5
NOFALLSVEL=10

################################################
#Stone Analyzer Compression
# 1-10 
# Default 1
################################################
STONESTEP=1

################################################
# 0-3
#
#  - Rectangle = 0
#  - Hanning = 1
#  - Hamming = 2
#  - Blackman = 3
#
# Default 0
################################################
STONEMODE=2

################################################
#Volume View
#SHOWVOSC = Show Volume On Slide Change
################################################
VVENABLE=True


XPOSITION=100
YPOSITION=100
HIDEIDLE=5000
SHOWVOSC=False


[INSTALL]
EXT=MP3;MP2;MP1;MPA;WAV;M3U;LS;


[PREFERENCE]
################################################
#Monitor BR variations
################################################
SHOWRATE=True

SLIDEACCEL=1
SERVER=False

################################################
#Option to Save ls at any file change
################################################
SAVEALS=True


################################################
#Option Save Stream Position
################################################
SSTREAMPOS=1


################################################
# Header Scan Level Accuracy
# 0-1024
#
# 128 Default
################################################
HINFOS=512


################################################
#Header Max Size Scan (In Byte, -1 is max)
################################################
HMAXSIZE=-1


################################################
#Open DialogBOX Char$ Buffer size in KByte
################################################
OBUFFER=32


################################################
#LCD232 enable, alpha test
#Tequire microhandler and LCD Hardware
################################################
MH=FALSE


[POS.INFO]
LISTFILE=mp3.ls
TOP=2505 
LEFT=5775 
NOMINIMIZED=True
ONTOP=False
SHOWLIST=True
COSC=False
ANALYZER=True
SPECTRUMMODE=3 
CPULESS=False
VOLUME=38 
LASTMP3=
POS=2703263
LOOP=False
RND=False
LSTTOP=4515
LSTLEFT=5775
LASTDIR=


[EQ]
0=0
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
