EXAMPLES = 3dtest basstest contest custloop dsptest fxtest livefx livespec \
	loadnget multi netradio plugins rectest speakers spectrum synth writewav

.PHONY: $(EXAMPLES)

all: $(EXAMPLES)

$(EXAMPLES):
	cd $@ && $(MAKE)
