[MAIN]
#Porta

PORT=8080

#Binding 0.0.0.0 tutti gli IP

BINDING=0.0.0.0

#Footer 
#0 = nessuno
#1 = Nero
#2 = Bianco
FOOTER=0

#Tutti i *FOLDER partono dall'Application Path
#
#Es:
#\WebRoot = App.Path & "\WebRoot"
#
#Note:
#Da non omettere la Root iniziale
#
#I Folder per i log e per i temporanei devono avere i permessi
#in scrittura per l'utente con cui gira il processo di mweb
#
#Web Root Folder := WEBFOLDER
#Temp Folder     := TMPFOLDER
#Logs Folder     := LOGFOLDER

WEBFOLDER=\WebRoot
TMPFOLDER=\Tmp
LOGFOLDER=\Log
PHPFOLDER=\PHP4.2.3

CUSTOMEXT=MHD
MAXFILEDIM = 4194304
MAXQREQ = 50

#Bandwdth Throttle in Kbit/s

BWT=64

#PIPE Buffer in Bytes

PIPEBUFFER=512

#Sound Engine Start
EXT=*.mp3
MP3ROOT=Z:\mp3
SELOGROOT=D:\VSS\CVSRoot\xmplayer\Source Other\BASSEngine\Logs
SEPATH=D:\VSS\CVSRoot\xmplayer\Source Other\BASSEngine
ENGINENAME=BassEngine
ENGINEEXE=BassEngine.exe

#PLUGIN MicroHandler
ENTRYPLUG=LCD232.Interface

EVLOG=False

[DENYURLSTRING]
#Stinghe non ammesse nel'URL

NOSTR1=..
NOSTR2=%

[BANNEDIP]
IP1=0.0.0.0 0.0.0.0

[TRUSTIP]
IP0=127.0.0.1 255.255.255.255